<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
<ItemGroup><PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.1" />
<Compile Include="../../CharacterQuestItemsPolicy.cs" Link="CharacterQuestItemsPolicy.cs" />
<Compile Include="../../CharacterQuestItemSessionHistory.cs" Link="CharacterQuestItemSessionHistory.cs" />
<Compile Include="../../CharacterQuestItems.cs" Link="CharacterQuestItems.cs" /></ItemGroup></Project>
